### ISSUE TITLE
predict_joint method for Machines

### ISSUE THREAD

**Issue by cscherrer** [cscherrer/SossMLJ.jl#66] opened 2020-08-24 20:35 UTC
Is this supposed to work?
```julia
julia> predictor_joint = MMI.predict_joint(mach, X)
ERROR: MethodError: no method matching predict_joint(::Machine{SossMLJModel{Soss.Model{NamedTuple{(:X, :s, :t),T} where T<:Tuple,TypeEncoding(begin
    σ ~ HalfNormal(t)
    p = size(X, 2)
    β ~ Normal(0, s) |> iid(p)
    η = X * β
    μ = η
    y ~ For(eachindex(μ)) do i
            Normal(μ[i], σ)
        end
end),TypeEncoding(Main)},var"#5#6",typeof(dynamicHMC),NamedTuple{(:s, :t),Tuple{Float64,Float64}},Symbol}}, ::NamedTuple{(:x1, :x2, :x3, :x4),Tuple{Array{Float64,1},Array{Float64,1},Array{Int64,1},Array{Int64,1}}})
Closest candidates are:
  predict_joint(::SossMLJModel, ::Any, ::Any) at /home/chad/git/SossMLJ.jl/src/models.jl:40
Stacktrace:
 [1] top-level scope at REPL[46]:1
 [2] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1088
```

There only seems to be one method defined:
```julia
julia> methods(MMI.predict_joint)
# 1 method for generic function "predict_joint":
[1] predict_joint(sm::SossMLJModel, fitresult, Xnew) in SossMLJ at /home/chad/git/SossMLJ.jl/src/models.jl:40
```

**Comment by cscherrer** [comment] 2020-08-24 20:35
cc @DilumAluthge

**Comment by DilumAluthge** [comment] 2020-08-24 20:38
That should work.

I think the issue is we're waiting for some PRs to be merged upstream:
- https://github.com/alan-turing-institute/MLJModelInterface.jl/pull/65
- https://github.com/alan-turing-institute/MLJ.jl/pull/646

Also, we need to require the latest release of MLJModelInterface, MLJBase, and MLJ.

Once all that is done, this should work.

**Comment by cscherrer** [comment] 2020-08-24 20:39
Great! In the mean time I'll try depending on those branches

**Comment by DilumAluthge** [comment] 2020-08-24 20:51
Yeah and for MLJBase, try using the latest registered release. If that doesn't work, try MLJBase master. If *that* doesn't work, try MLJBase dev branch.

The workflow for MLJ is that they first merge PRs into dev, and then periodically they merge dev into master and then register a release off of master.

**Comment by cscherrer** [comment] 2020-08-24 20:56
Ah ok, so it does work with this setup:
```julia
(SossMLJ) pkg> st
Project SossMLJ v0.1.0
Status `~/git/SossMLJ.jl/Project.toml`
  [324d7699] CategoricalArrays v0.8.1
  [31c24e10] Distributions v0.23.8
  [add582a8] MLJ v0.12.0 `https://github.com/DilumAluthge/MLJ.jl#patch-1`
  [a7f614a8] MLJBase v0.14.8 `https://github.com/alan-turing-institute/MLJBase.jl.git#dev`
  [e80e1ace] MLJModelInterface v0.3.3 `https://github.com/DilumAluthge/MLJModelInterface.jl#patch-1`
  [0987c9cc] MonteCarloMeasurements v0.9.5
  [d9ec5142] NamedTupleTools v0.13.6
  [8ce77f84] Soss v0.13.1
  [bd369af6] Tables v1.0.5
  [10745b16] Statistics
```

**Comment by DilumAluthge** [comment] 2020-08-24 20:59
Cool. Let's leave this open as a reminder. We can close it when this works with just registered versions.

**Closed as completed** 2020-08-26 23:58 UTC
Labels: MLJ upstream
